sudo: required

language: python
python:
  - 2.7

services:
  - docker

before_install:
  - docker pull juanmahidalgo/match
  - docker run -it juanmahidalgo/match /bin/sh -c " bundle exec foreman start;"
script:
  - bundle exec rake test
